### ISSUE TITLE
The word 'false' is saved in empty text repeater fields in v2.4.0

### ISSUE THREAD

**Issue by lumpysimon** [CMB2/CMB2#1138]
This issue affects v2.4.0 but not v2.3.0

When adding new items to a repeater text field and leaving them blank, the items should not be saved. In v2.4.0 the items are saved and contain the word `false`. This means when displaying the field values on the front end, the word `false` is returned and displayed.

To reproduce:

* Create a field with `'type' => 'text'` and `'repeatable' => true`
* Add an item to the field with a value in it
* Add a second item with no value
* Save the post
* The second item will contain the word false

<img width="662" alt="screen shot 2018-05-25 at 09 13 35" src="https://user-images.githubusercontent.com/625372/40533872-fe481fb8-5ffb-11e8-867d-a308a1ad6f11.png">

**Comment by jtsternberg** [comment]
Fixed in 2.4.1. Thank you for the helpful bug report.

**Comment by JiveDig** [comment]
@jtsternberg I'm testing 2.4.1 now and still getting false in a repeatable WYSIWYG field. Tested on 2 different installs.  If I add `'default' => '',` to the WYSIWYG field, then it's fine.

**Comment by jtsternberg** [comment]
@JiveDig as always, can you pretty please provide your configuration code so we can test w/ the same thing?

**Comment by JiveDig** [comment]
Sorry @jtsternberg, I think i was too excited for 🍺 on Memorial Day weekend ;P

```
add_action('cmb2_init', function() {

	$cmb = new_cmb2_box([
		'id'           => 'test',
		'title'        => 'Test',
		'object_types' => ['post'],
		'context'      => 'normal',
		'priority'     => 'default'
	]);

	$group_field_id = $cmb -> add_field([
		'id'   => 'group',
		'type' => 'group'

	]);

	$cmb->add_group_field( $group_field_id, array(
		'name' => __( 'Content', 'textdomain' ),
		'id'   => 'content',
		'type' => 'wysiwyg',
	) );

}, 20, 2 );
```

**Comment by jtsternberg** [comment]
Ha, I hear that. It should be fixed with 2.4.2. Please let me know.

**Comment by JiveDig** [comment]
Yessir, works in 2.4.2 thanks!

**Comment by lumpysimon** [comment]
Thanks @jtsternberg for the quick fix on this, all working great again now.
